### ISSUE TITLE
Issue on the api route /api/v1/deviceport/:deviceid/patchcandidates 

### ISSUE THREAD

**Issue by gabrielamarqs** [opendcim/openDCIM#1469]
```
Slim Application Error
The application could not run because of the following error:

Details
Type: ErrorException
Code: 8
Message: Undefined index: PortNumber
File: /opt/openDCIM/opendcim/api/v1/getRoutes.php
Line: 552
Trace
#0 /opt/openDCIM/opendcim/api/v1/getRoutes.php(552): Slim\Slim::handleErrors(8, 'Undefined index...', '/opt/openDCIM/o...', 552, Array)
#1 [internal function]: {closure}('312')
#2 /opt/openDCIM/opendcim/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#3 /opt/openDCIM/opendcim/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#4 /opt/openDCIM/opendcim/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#5 /opt/openDCIM/opendcim/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#6 /opt/openDCIM/opendcim/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#7 /opt/openDCIM/opendcim/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#8 /opt/openDCIM/opendcim/api/v1/index.php(187): Slim\Slim->run()
#9 {main}
```

I'm using both the versions 19.1 and 23.02, and that api route doesn't work 
And both of them is giving me that error

**Comment by wilpig** [comment]
Upgrade to 23.04
